INSERT INTO idl_menu (menu_id,name,title,menu_type,parent_id,access_code,"path",component,icon,affix_tab,hidden_in_menu,redirect,keep_alive,iframe_src,link,"query",open_in_new_window,no_basic_layout,ignore_access,order_no,status,is_leaf,remark,delete_flag,tenant_id,revision,created_by,created_time,updated_by,updated_time) VALUES
	 ('1','Dashboard','page.dashboard.title','menu','0',NULL,'/dashboard','BasicLayout','lucide:layout-dashboard',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('11','Analytics','page.dashboard.analytics','menu','1',NULL,'/analytics','/dashboard/analytics/index','lucide:area-chart',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,11,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('12','Workspace','page.dashboard.workspace','menu','1',NULL,'/workspace','/dashboard/workspace/index','carbon:workspace',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,12,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('2','Management','management.title','menu','0',NULL,'/management','BasicLayout','ic:sharp-manage-accounts',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('21','Menu','permission.menu.title','menu','2',NULL,'/permission/menu/list','/permission/menu/list','material-symbols:menu',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,21,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('22','Role','permission.role.title','menu','2',NULL,'/permission/role/list','/permission/role/list','carbon:user-role',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,22,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('3','Infra','infra.title','menu','0',NULL,'/infra','BasicLayout','streamline:industry-innovation-and-infrastructure',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('31','ConfigParam','infra.configParam.title','menu','2',NULL,'/infra/config-param/list','/infra/config-param/list','carbon:parameter',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,31,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('32','DataDict','infra.dataDict.title','menu','2',NULL,'/infra/data-dict/list','/infra/data-dict/list','streamline:dictionary-language-book',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,32,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('4','Message','message.title','menu','0',NULL,'/message','BasicLayout','ant-design:message-outlined',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO idl_menu (menu_id,name,title,menu_type,parent_id,access_code,"path",component,icon,affix_tab,hidden_in_menu,redirect,keep_alive,iframe_src,link,"query",open_in_new_window,no_basic_layout,ignore_access,order_no,status,is_leaf,remark,delete_flag,tenant_id,revision,created_by,created_time,updated_by,updated_time) VALUES
	 ('41','MessageTemplate','message.messageTemplate.title','menu','4',NULL,'/message/message-template/list','/message/message-template/list','tdesign:template',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,41,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('42','MessageHistory','message.messageHistory.title','menu','4',NULL,'/message/message-history/list','/message/message-history/list','ep:message',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,42,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('43','MessageNotification','message.messageNotification.title','menu','4',NULL,'/message/message-notification/list','/message/message-notification/list','mingcute:notification-fill',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,43,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('45','MyNotification','message.myNotification.title','menu','4',NULL,'/message/notification/my-list','/message/notification/my-list','',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,45,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('5','User','user.title','menu','0',NULL,'/user','BasicLayout','mdi:users',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,5,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('51','UserInfo','user.userInfo.title','menu','5',NULL,'/user/user-info/list','/user/user-info/list','hugeicons:user',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,51,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('53','UserLogin','user.userLogin.title','menu','5',NULL,'/user/user-login/list','/user/user-login/list','material-symbols:login',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,53,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('54','UserThirdParty','user.userThirdParty.title','menu','5',NULL,'/user/user-third-party/list','/user/user-third-party/list','material-symbols:identity-platform',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,54,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('6','My','my.title','menu','0',NULL,'/my','BasicLayout','',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('61','MyIndex','my.title','menu','6',NULL,'/my/index','/my/index','',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,61,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO idl_menu (menu_id,name,title,menu_type,parent_id,access_code,"path",component,icon,affix_tab,hidden_in_menu,redirect,keep_alive,iframe_src,link,"query",open_in_new_window,no_basic_layout,ignore_access,order_no,status,is_leaf,remark,delete_flag,tenant_id,revision,created_by,created_time,updated_by,updated_time) VALUES
	 ('7','Storage','storage.title','menu','0',NULL,'/storage','BasicLayout','mdi:storage',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7,'enabled',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL),
	 ('71','FileDetail','storage.fileDetail.title','menu','2',NULL,'/storage/file-detail/list','/storage/file-detail/list','material-symbols:storage',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,71,'enabled',1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL);
